version: 2.1

orbs:
  python: circleci/python@2.0.3
  discord: teka23/discord@0.1.0

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.12.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          packages: poetry
      - restore_cache:
          keys:
            - poetry-{{ checksum "poetry.lock" }}
      - run:
          name: Install dependencies
          command: poetry install
      - save_cache:
          paths:
            - ~/.cache/pypoetry
          key: poetry-{{ checksum "poetry.lock" }}
      - run:
          name: Run tests
          command: poetry run pytest
      - discord/status:
          success_message: "Build and test succeeded!"
          failure_message: "Build and test failed."
          webhook: ${DISCORD_WEBHOOK}
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    docker:
      - image: cimg/python:3.9
    steps:
      - attach_workspace:
          at: ~/project
      - python/install-packages:
          pkg-manager: pip
          packages: poetry
      - run:
          name: Install Railway CLI
          command: npm i -g @railway/cli
      - run:
          name: Deploy to Railway
          command: |
            railway up --service your-discord-bot-service
      - discord/status:
          success_message: "Deployment to Railway succeeded!"
          failure_message: "Deployment to Railway failed."
          webhook: ${DISCORD_WEBHOOK}

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: main
