version: 2.1

orbs:
  python: circleci/python@2.1.1
  discord: antonioned/discord@0.1.0

jobs:
  test:
    docker:
      - image: cimg/python:3.12.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          args: poetry
      - run:
          name: Run tests
          command: poetry run python -m unittest discover tests

  deploy:
    docker:
      - image: cimg/python:3.12.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          args: poetry
      - run:
          name: Install Railway CLI
          command: npm i -g @railway/cli
      - run:
          name: Deploy to Railway
          command: |
            poetry run railway up --service your-discord-bot-service

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
